# Definiert die Ausführungsstufen in der Pipeline
stages:
  - build
  - deploy

# Variablen, die in der Pipeline verwendet werden können
variables:
  DOCKER_NAME: "vulnerability-dashboard" # must be lowercase
  DOCKER_TAG: "latest"
  DOCKER_FILE: "Dockerfile"
  DOCKER_HOST: tcp://10.97.2.116:2375
  DOCKER_REGISTRY: "10.97.2.116:5000"
  DOCKER_TLS_CERTDIR: ""

image: docker:stable

# Definiert den Build-Job
build:
  stage: build
  script:
    - docker build -f $DOCKER_FILE -t $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG . > build.log
    - docker push $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG >> build.log
  artifacts:
    paths:
      - build.log

# Definiert den Deployment-Job
deploy:
  stage: deploy
  script:
    - docker service update --image $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG $DOCKER_NAME > deploy.log
  artifacts:
    paths:
      - deploy.log
